"""Prepare Kev devtools-v1 judgment rows for `mtp-capture features` (no model, no GPU).

Reads locally supplied, pinned Kev `devtools-v1` files (never downloads):

    KEV_DIR/manifest.json       sha256 must equal PINNED_MANIFEST_SHA256
    KEV_DIR/train.jsonl         Kev partition train       -> train + calibration
    KEV_DIR/development.jsonl   Kev partition development -> validation
    KEV_DIR/test.jsonl          Kev partition test        -> test (locked)

Every file's sha256, byte size, record count and per-source count must match the
manifest; every record is schema-checked, including records that are excluded.

Only the audited coding questions with native labels are converted (no LLM
relabeling): CodeReviewer `needs_comment` and CommitPackFT `message_match`.
FlakeFlagger and commit-change-type are excluded (Kev's later label audit: the
input does not determine the label), Aegis is outside the coding focus, and
When2Call / prompt-injection are evaluation-only. Every excluded question row is
counted in the report by reason; nothing is dropped silently.

Calibration is carved from Kev's train partition by whole `group_id`, in a
seeded hash order, per source. Development becomes validation and test stays
the locked test split. Record (`row_sha256`), group, state text (exact and
whitespace/case-normalised) and rendered-text overlap across splits is an error.

Each output row is the capture input contract of `mtp-capture features`:

    {"id": "kev-devtools-v1/<task>/<row_sha256>", "text": <rendered prompt>,
     "token_end_offsets": [<option 1 end>, ..., <decision end>],
     "metadata": {"split", "target", "options", "option_labels", "native_label",
                  "task", "source", "question", "kev_id", "group_id",
                  "kev_partition", "row_sha256", "text_sha256", "repo_licence",
                  "renderer"}}

Rendered text (RENDERER):

    State:\\n<state>\\n\\nQuestion: <instructions>\\nOptions:\\n
    A) <option>\\n B) <option>\\n ... Decision:

Option order is a per-row deterministic permutation (sha256 of seed, record and
option); `target` indexes the gold option in that order. Offsets are exclusive
UTF-8 byte ends: each option endpoint includes its line's "\\n", the decision
endpoint is the end of "Decision:". The native Bonsai tokenizer in
`mtp-capture` resolves them to exact token boundaries, or rejects the row.

`--pilot-rows N` keeps, per split and task, whole groups in a seeded hash order
while they fit in N rows; the rest are reported as `pilot_cap`. A pilot only
exercises the pipeline; it is not evidence of quality.

Output: a new directory (never overwritten) with `rows.jsonl` and `report.json`
(provenance, hashes, licences/attribution, counts, exclusions, caveats).

`--dataset hard-v1` instead reads Kev's synthetic hard-v1 suite (pinned
manifest; train.jsonl regenerated by Kev's generator, see
`kaggle_judgment_job.py --regenerate-hard-v1`). It reads only train and
development, never test; calibration is train template 3, validation is
development (template 4); noul/choice/score questions become 2-6 options;
long_policy is excluded in round 1 (`--include-long-policy` keeps it). See
the hard-v1 section below. The default devtools-v1 output is byte-identical
to earlier versions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

KEV_REPOSITORY = "https://github.com/jaredpalmer/kev"
KEV_REVISION = "5e42a7a03f28134853dd3ff77461457e921e5ec1"
KEV_BASE_URL = f"https://raw.githubusercontent.com/jaredpalmer/kev/{KEV_REVISION}/evals/devtools-v1"
PINNED_MANIFEST_SHA256 = (
    "d0f7cf40cec3284684f8b2fe8f440a5f0cc40fe4a78db108eca47a5fbd141b0f"
)
KEV_VERSION = "devtools-v1"
FORMAT = "local-ai.judgment-capture-rows.v1"
RENDERER = "kev-devtools-v1-judgment-render.v1"
DEFAULT_SEED = "local-ai-judgment-v1"

# Kev partition file -> output split. Calibration is carved from train.
PARTITIONS = {
    "train": ("train.jsonl", "train"),
    "development": ("development.jsonl", "validation"),
    "test": ("test.jsonl", "test"),
}
SPLIT_ORDER = ("train", "calibration", "validation", "test")

# Converted questions, keyed by Kev question `src`.
TASKS = {
    "codereviewer_needs_comment": {
        "source": "codereviewer",
        "question": "needs_comment",
    },
    "commitpackft_message": {"source": "commitpackft", "question": "message_match"},
}
# Every other known question `src`, with the reason it is not converted.
EXCLUDED = {
    "commitpackft_type": "label_audit_input_does_not_determine_label",
    "flakeflagger_flaky": "label_audit_input_does_not_determine_label",
    "aegis_unsafe": "outside_coding_focus",
    "aegis_category": "outside_coding_focus",
    "when2call_action": "evaluation_only",
    "prompt_injection": "evaluation_only",
}
KNOWN_SOURCES = {
    "codereviewer",
    "commitpackft",
    "flakeflagger",
    "aegis",
    "when2call",
    "prompt_injection",
}
NOUL_OPTIONS = (("Yes", True), ("No", False))
RECORD_KEYS = {"state", "questions", "_meta"}
META_REQUIRED = {
    "id",
    "source",
    "group_id",
    "row_sha256",
    "text_sha256",
    "split",
    "variant",
}
NOUL_KEYS = {"type", "instructions", "label", "src"}
HEX64 = re.compile(r"[0-9a-f]{64}")
CAVEATS = [
    "Preparation does not run training; these rows alone do not establish quality.",
    (
        "Labels are Kev's native labels: CodeReviewer is human; CommitPackFT message "
        "match is by construction (own subject vs another commit's subject)."
    ),
    "CommitPackFT negative-subject reuse across splits has not been audited.",
    "Kev balanced labels by sampling; rates are not natural rates.",
    "Kev's CodeReviewer `id` is not unique; `row_sha256` identifies records.",
    "Frozen Bonsai features may not match Kev's adapter-trained representations.",
    "A small pilot only exercises the pipeline; its metrics prove nothing.",
    "Repository licences were recorded by Kev at lookup time, not collection time.",
]


class PrepareError(ValueError):
    """The supplied Kev files or options cannot produce a valid dataset."""


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def hash_key(*parts: str) -> str:
    return sha256_hex("\0".join(parts).encode("utf-8"))


def _strict_object(pairs):
    keys = [key for key, _ in pairs]
    if len(keys) != len(set(keys)):
        raise PrepareError(f"duplicate JSON key in {keys}")
    return dict(pairs)


def load_manifest(kev_dir: Path, expected_sha256: str) -> tuple[dict, str]:
    path = kev_dir / "manifest.json"
    data = path.read_bytes()
    digest = sha256_hex(data)
    if digest != expected_sha256:
        raise PrepareError(
            f"manifest.json sha256 {digest} does not match pinned {expected_sha256}"
        )
    manifest = json.loads(data, object_pairs_hook=_strict_object)
    if manifest.get("version") != KEV_VERSION:
        raise PrepareError(f"unsupported manifest version {manifest.get('version')!r}")
    if manifest.get("partitions") != list(PARTITIONS):
        raise PrepareError(f"unsupported partitions {manifest.get('partitions')!r}")
    if "test" not in manifest.get("locked", []):
        raise PrepareError("manifest does not lock the test partition")
    eval_only = set(manifest.get("eval_only_sources", []))
    for task, spec in TASKS.items():
        if spec["source"] in eval_only:
            raise PrepareError(f"{task}: source {spec['source']} is evaluation-only")
        source = manifest.get("sources", {}).get(spec["source"])
        if not isinstance(source, dict) or not source.get("trainable"):
            raise PrepareError(f"manifest has no trainable source {spec['source']!r}")
        for key in ("licence", "licence_url", "attribution", "label_provenance"):
            if not isinstance(source.get(key), str) or not source[key]:
                raise PrepareError(f"manifest source {spec['source']} lacks {key}")
    return manifest, digest


def load_partition(kev_dir: Path, partition: str, manifest: dict) -> list[dict]:
    name = PARTITIONS[partition][0]
    entry = manifest.get("files", {}).get(name)
    if not isinstance(entry, dict):
        raise PrepareError(f"manifest has no files entry for {name}")
    data = (kev_dir / name).read_bytes()
    digest = sha256_hex(data)
    if digest != entry.get("sha256"):
        raise PrepareError(
            f"{name}: sha256 {digest} does not match manifest {entry.get('sha256')}"
        )
    if len(data) != entry.get("bytes"):
        raise PrepareError(
            f"{name}: {len(data)} bytes, manifest says {entry.get('bytes')}"
        )
    lines = data.decode("utf-8").split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    records = []
    for number, line in enumerate(lines, 1):
        where = f"{name}:{number}"
        try:
            record = json.loads(line, object_pairs_hook=_strict_object)
        except (json.JSONDecodeError, PrepareError) as error:
            raise PrepareError(f"{where}: invalid JSON record: {error}") from error
        check_record(record, partition, where)
        records.append(record)
    if len(records) != entry.get("records"):
        raise PrepareError(
            f"{name}: {len(records)} records, manifest says {entry.get('records')}"
        )
    by_source = dict(Counter(r["_meta"]["source"] for r in records))
    if by_source != entry.get("by_source"):
        raise PrepareError(
            f"{name}: per-source counts {by_source} != manifest {entry.get('by_source')}"
        )
    return records


def check_record(record, partition: str, where: str) -> None:
    """Validate the common schema of every record and the full schema of converted ones."""
    if not isinstance(record, dict) or set(record) != RECORD_KEYS:
        raise PrepareError(
            f"{where}: record must have exactly the keys {sorted(RECORD_KEYS)}"
        )
    meta = record["_meta"]
    if not isinstance(meta, dict) or not META_REQUIRED <= set(meta):
        raise PrepareError(f"{where}: _meta must include {sorted(META_REQUIRED)}")
    for key in ("id", "source", "group_id"):
        if not isinstance(meta[key], str) or not meta[key]:
            raise PrepareError(f"{where}: _meta.{key} must be a non-empty string")
    for key in ("row_sha256", "text_sha256"):
        if not isinstance(meta[key], str) or not HEX64.fullmatch(meta[key]):
            raise PrepareError(f"{where}: _meta.{key} must be a sha256 hex digest")
    if meta["source"] not in KNOWN_SOURCES:
        raise PrepareError(f"{where}: unsupported source {meta['source']!r}")
    if meta["split"] != partition:
        raise PrepareError(
            f"{where}: _meta.split {meta['split']!r} in partition {partition}"
        )
    if meta["variant"] != "clean":
        raise PrepareError(f"{where}: unsupported variant {meta['variant']!r}")
    questions = record["questions"]
    if not isinstance(questions, dict) or not questions:
        raise PrepareError(f"{where}: questions must be a non-empty object")
    for name, question in questions.items():
        src = question.get("src") if isinstance(question, dict) else None
        if src in TASKS:
            spec = TASKS[src]
            if (meta["source"], name) != (spec["source"], spec["question"]):
                raise PrepareError(
                    f"{where}: question {name!r} with src {src!r} "
                    f"in source {meta['source']!r}"
                )
            if set(question) != NOUL_KEYS or question["type"] != "noul":
                raise PrepareError(
                    f"{where}: {src} must be a noul question with keys "
                    f"{sorted(NOUL_KEYS)}"
                )
            if (
                not isinstance(question["instructions"], str)
                or not question["instructions"]
            ):
                raise PrepareError(
                    f"{where}: {src} instructions must be non-empty text"
                )
            if type(question["label"]) is not bool:
                raise PrepareError(f"{where}: {src} label must be a boolean")
            render_state(meta["source"], record["state"], where)
        elif src not in EXCLUDED:
            raise PrepareError(f"{where}: unsupported question {name!r} (src {src!r})")


def render_state(source: str, state, where: str) -> str:
    if source == "codereviewer":
        if (
            not isinstance(state, dict)
            or "diff" not in state
            or not set(state) <= {"diff", "lines_before_hunk"}
            or not all(isinstance(v, str) for v in state.values())
        ):
            raise PrepareError(f"{where}: unsupported codereviewer state schema")
        parts = []
        if "lines_before_hunk" in state:
            parts.append("Context before hunk:\n" + state["lines_before_hunk"] + "\n\n")
        parts.append("Diff:\n" + state["diff"])
        return "".join(parts)
    if source == "commitpackft":
        if not isinstance(state, str) or not state.strip():
            raise PrepareError(f"{where}: unsupported commitpackft state schema")
        return "Diff:\n" + state
    raise PrepareError(f"{where}: no renderer for source {source!r}")


def permute_options(options, seed: str, record_key: str):
    """Deterministic per-row order: options sorted by sha256(seed, record, option)."""
    return sorted(options, key=lambda option: hash_key(seed, record_key, option[0]))


def render(state_text: str, instructions: str, options) -> tuple[str, list[int]]:
    """Return (text, exclusive UTF-8 byte ends of each option line and of the cue)."""
    pieces = ["State:\n", state_text, "\n\nQuestion: ", instructions, "\nOptions:\n"]
    size = sum(len(piece.encode("utf-8")) for piece in pieces)
    ends = []
    for index, (label, _) in enumerate(options):
        line = f"{chr(ord('A') + index)}) {label}\n"
        pieces.append(line)
        size += len(line.encode("utf-8"))
        ends.append(size)
    pieces.append("Decision:")
    text = "".join(pieces)
    ends.append(len(text.encode("utf-8")))
    return text, ends


def normalized_text_hash(text: str) -> str:
    return sha256_hex(" ".join(text.casefold().split()).encode("utf-8"))


def candidates(records_by_partition, seed: str, excluded):
    """Yield one candidate row per converted question; count every other question."""
    seen_rows = {}
    for partition, records in records_by_partition.items():
        for record in records:
            meta = record["_meta"]
            if meta["row_sha256"] in seen_rows:
                raise PrepareError(
                    f"row_sha256 {meta['row_sha256']} appears in "
                    f"{seen_rows[meta['row_sha256']]} and {partition}"
                )
            seen_rows[meta["row_sha256"]] = partition
            converted = 0
            for question in record["questions"].values():
                src = question["src"]
                if src not in TASKS:
                    excluded[EXCLUDED[src]][partition][src] += 1
                    continue
                converted += 1
                state_text = render_state(meta["source"], record["state"], meta["id"])
                key = f"{meta['row_sha256']}/{src}"
                options = permute_options(NOUL_OPTIONS, seed, key)
                text, ends = render(state_text, question["instructions"], options)
                labels = [value for _, value in options]
                yield {
                    "id": f"kev-{KEV_VERSION}/{src}/{meta['row_sha256']}",
                    "text": text,
                    "token_end_offsets": ends,
                    "metadata": {
                        "split": PARTITIONS[partition][1],
                        "target": labels.index(question["label"]),
                        "options": [label for label, _ in options],
                        "option_labels": labels,
                        "native_label": question["label"],
                        "task": src,
                        "source": meta["source"],
                        "question": TASKS[src]["question"],
                        "kev_id": meta["id"],
                        "group_id": meta["group_id"],
                        "kev_partition": partition,
                        "row_sha256": meta["row_sha256"],
                        "text_sha256": meta["text_sha256"],
                        "repo_licence": meta.get("repo_licence"),
                        "renderer": RENDERER,
                    },
                    "_state": json.dumps(
                        record["state"], sort_keys=True, ensure_ascii=False
                    ),
                    "_state_text": state_text,
                }
            if converted == 0 and meta["source"] in {
                t["source"] for t in TASKS.values()
            }:
                excluded["no_supported_question"][partition][meta["source"]] += 1


def _groups(rows):
    groups = defaultdict(list)
    for row in rows:
        groups[row["metadata"]["group_id"]].append(row)
    return groups


def carve_calibration(rows, seed: str, fraction: float, min_groups: int) -> None:
    """Move whole train groups to calibration, per task, in seeded hash order."""
    by_task = defaultdict(list)
    for row in rows:
        if row["metadata"]["split"] == "train":
            by_task[row["metadata"]["task"]].append(row)
    for task, task_rows in sorted(by_task.items()):
        groups = _groups(task_rows)
        if len(groups) < 2 * min_groups:
            raise PrepareError(
                f"{task}: {len(groups)} train groups; need {2 * min_groups} "
                "to carve group-disjoint calibration"
            )
        wanted = math.ceil(fraction * len(task_rows))
        taken = 0
        order = sorted(groups, key=lambda g: hash_key(seed, "calibration", g))
        for chosen, group in enumerate(order):
            if taken >= wanted and chosen >= min_groups:
                break
            if len(groups) - chosen <= min_groups:
                raise PrepareError(
                    f"{task}: calibration would leave fewer than "
                    f"{min_groups} train groups"
                )
            for row in groups[group]:
                row["metadata"]["split"] = "calibration"
            taken += len(groups[group])


def apply_pilot_cap(rows, seed: str, cap: int, excluded) -> list[dict]:
    """Keep whole groups per (split, task) in seeded hash order while they fit in `cap`."""
    by_cell = defaultdict(list)
    for row in rows:
        by_cell[(row["metadata"]["split"], row["metadata"]["task"])].append(row)
    kept = []
    for (split, task), cell in sorted(by_cell.items()):
        groups = _groups(cell)
        used = 0
        for group in sorted(groups, key=lambda g: hash_key(seed, "pilot", split, g)):
            members = groups[group]
            if used + len(members) <= cap:
                kept.extend(members)
                used += len(members)
            else:
                excluded["pilot_cap"][split][task] += len(members)
    return kept


def check_splits(rows, min_groups: int) -> dict:
    """Leakage, uniqueness, group-count and label-diversity checks; return counts."""
    check_overlaps(rows)
    counts = {}
    for split in SPLIT_ORDER:
        counts[split] = {}
        for task in TASKS:
            cell = [
                r
                for r in rows
                if r["metadata"]["split"] == split and r["metadata"]["task"] == task
            ]
            groups = {r["metadata"]["group_id"] for r in cell}
            labels = Counter(str(r["metadata"]["native_label"]).lower() for r in cell)
            if len(groups) < min_groups:
                raise PrepareError(
                    f"{split}/{task}: {len(groups)} groups, need {min_groups}"
                )
            if len(labels) < 2:
                raise PrepareError(
                    f"{split}/{task}: only labels {dict(labels)}; need both"
                )
            counts[split][task] = {
                "rows": len(cell),
                "groups": len(groups),
                "native_labels": dict(sorted(labels.items())),
                "targets": dict(
                    sorted(Counter(str(r["metadata"]["target"]) for r in cell).items())
                ),
            }
    return counts


def check_overlaps(rows) -> None:
    """Record, group, state (exact and normalised), source-digest, text and id
    overlap across splits is an error; within a split only one record's own
    questions may share a state, and only one group may span several records."""
    owners = {
        kind: {}
        for kind in (
            "record",
            "group",
            "state",
            "normalized_state",
            "kev_text_sha256",
            "text",
            "id",
        )
    }
    for row in rows:
        meta = row["metadata"]
        keys = {
            "record": "/".join((meta["row_sha256"], meta["task"], meta["question"])),
            "group": meta["group_id"],
            "state": sha256_hex(row["_state"].encode("utf-8")),
            "normalized_state": normalized_text_hash(row["_state_text"]),
            "kev_text_sha256": meta["text_sha256"],
            "text": sha256_hex(row["text"].encode("utf-8")),
            "id": row["id"],
        }
        for kind, key in keys.items():
            other = owners[kind].setdefault(key, row)
            if other is row:
                continue
            same_split = other["metadata"]["split"] == meta["split"]
            if kind == "group" and same_split:
                continue
            if (
                kind in ("state", "normalized_state", "kev_text_sha256")
                and same_split
                and (other["metadata"]["row_sha256"] == meta["row_sha256"])
            ):
                continue  # several questions of one record
            raise PrepareError(
                f"{kind} overlap between {other['id']} "
                f"({other['metadata']['split']}) and {row['id']} ({meta['split']})"
            )


def prepare(
    kev_dir: Path,
    out: Path,
    *,
    seed: str = DEFAULT_SEED,
    calibration_fraction: float = 0.1,
    pilot_rows: int | None = None,
    min_groups: int = 2,
    manifest_sha256: str = PINNED_MANIFEST_SHA256,
) -> dict:
    """Validate, convert and write `out/rows.jsonl` and `out/report.json`."""
    kev_dir, out = Path(kev_dir), Path(out)
    if out.exists() or out.is_symlink():
        raise PrepareError(f"{out} already exists; refusing to overwrite")
    if not 0 < calibration_fraction < 1:
        raise PrepareError("calibration fraction must be in (0, 1)")
    if min_groups < 1 or (pilot_rows is not None and pilot_rows < 1):
        raise PrepareError("min groups and pilot rows must be positive")
    manifest, manifest_digest = load_manifest(kev_dir, manifest_sha256)
    records = {p: load_partition(kev_dir, p, manifest) for p in PARTITIONS}
    excluded = defaultdict(lambda: defaultdict(Counter))
    rows = list(candidates(records, seed, excluded))
    carve_calibration(rows, seed, calibration_fraction, min_groups)
    if pilot_rows is not None:
        rows = apply_pilot_cap(rows, seed, pilot_rows, excluded)
    counts = check_splits(rows, min_groups)
    rows.sort(
        key=lambda r: (
            SPLIT_ORDER.index(r["metadata"]["split"]),
            hash_key(seed, "order", r["id"]),
        )
    )
    payload = _rows_payload(rows)
    kev_ids = Counter(r["metadata"]["kev_id"] for r in rows)
    report = {
        "format": FORMAT,
        "renderer": RENDERER,
        "options": {
            "seed": seed,
            "calibration_fraction": calibration_fraction,
            "pilot_rows": pilot_rows,
            "min_groups": min_groups,
        },
        "kev": {
            "repository": KEV_REPOSITORY,
            "revision": KEV_REVISION,
            "manifest_url": f"{KEV_BASE_URL}/manifest.json",
            "manifest_sha256": manifest_digest,
            "manifest_pinned": manifest_digest == PINNED_MANIFEST_SHA256,
            "version": manifest["version"],
            "code_licence": "Apache-2.0 (Kev repository); data per source below",
            "files": {
                name: {
                    k: manifest["files"][name][k]
                    for k in ("sha256", "bytes", "records")
                }
                for name, _ in PARTITIONS.values()
            },
            "label_protocol": manifest.get("label_protocol"),
        },
        "split_map": {
            "train": "train minus calibration groups",
            "calibration": "whole train groups, seeded hash order",
            "validation": "development",
            "test": "test (locked)",
        },
        "tasks": {
            task: {
                **spec,
                **{
                    k: manifest["sources"][spec["source"]].get(k)
                    for k in (
                        "licence",
                        "licence_url",
                        "attribution",
                        "label_provenance",
                        "licence_check",
                    )
                },
                "repo_licences": dict(
                    sorted(
                        Counter(
                            str(r["metadata"]["repo_licence"])
                            for r in rows
                            if r["metadata"]["task"] == task
                        ).items()
                    )
                ),
            }
            for task, spec in TASKS.items()
        },
        "excluded_questions": EXCLUDED,
        "counts": counts,
        "excluded_rows": {
            reason: {
                part: dict(sorted(c.items())) for part, c in sorted(by_part.items())
            }
            for reason, by_part in sorted(excluded.items())
        },
        "repeated_kev_ids": sum(n > 1 for n in kev_ids.values()),
        "output": {
            "rows": "rows.jsonl",
            "row_count": len(rows),
            "sha256": sha256_hex(payload),
        },
        "caveats": CAVEATS,
    }
    out.mkdir(parents=True)
    with open(out / "rows.jsonl", "xb") as handle:
        handle.write(payload)
    with open(out / "report.json", "x", encoding="utf-8") as handle:
        handle.write(
            json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        )
    return report


# ---------------------------------------------------------------------------
# Kev hard-v1 (`--dataset hard-v1`)
#
# Kev's deterministic generator (scripts/build_hard_v1.py at HARD_REVISION)
# writes manifest.json (pinned below), development.jsonl and test.jsonl (in
# git) and train.jsonl (gitignored; regenerated byte-identically by the
# generator, which needs the pinned Qwen3.5-4B-Base tokenizer for its length
# and context admission). Only train and development are ever opened: test
# (template 5) stays locked, unread and unscored until the training recipe is
# frozen. Splits follow the surface template, so every evaluation split
# measures transfer to an unseen phrasing:
#
#     Kev train, templates 0-2  -> train
#     Kev train, template 3     -> calibration
#     Kev development (t4)      -> validation
#     Kev test (t5)             -> not read
#
# Question translation (labels are Kev's programmatic labels, unchanged):
#   noul   -> "Yes"/"No" (Kev keys true/false), seeded per-row order as in
#             devtools; criteria descriptions, if any, as "Yes: <desc>".
#   choice -> 3-6 options in Kev's order (its generator balances the gold
#             position); key "not_enough_information" reads
#             "not enough information"; a description is appended as
#             "<name>: <desc>". Single-letter keys (a-f) are anonymous: the
#             option is its description alone.
#   score  -> the 6 ordered level descriptions; target is the level index.
# `option_descriptions=False` drops descriptions from named choice/noul
# options (anonymous options keep theirs: it is their only content). The
# devtools renderer and its bytes are unchanged.
# ---------------------------------------------------------------------------

HARD_VERSION = "hard-v1"
HARD_REVISION = "62c91838b9a6adc5b386cbeae8ed73daa36ce220"
HARD_BASE_URL = f"https://raw.githubusercontent.com/jaredpalmer/kev/{HARD_REVISION}/evals/hard-v1"
HARD_MANIFEST_SHA256 = (
    "9d8dd335f5a73840b144c987ee91bb0513301128c474a7a4cd3f754a130cfa5c"
)
HARD_TRAIN_SHA256 = "a08ca9c5ba5d365967876d7d88753cf876624be8553df5af3dca8973e4a1aa4d"
HARD_TOKENIZER = {
    "model": "Qwen/Qwen3.5-4B-Base",
    "revision": "1001bb4d826a52d1f399e183466143f4da7b741b",
}
HARD_RENDERER = "kev-hard-v1-judgment-render.v1"
HARD_RENDERER_NO_DESCRIPTIONS = "kev-hard-v1-judgment-render.v1-no-descriptions"
HARD_FAMILIES = (
    "long_policy",
    "tradeoff",
    "probability",
    "multi_hop",
    "temporal_numeric",
    "judge",
    "ambiguous",
)
HARD_TEMPLATES = {"train": [0, 1, 2, 3], "development": [4], "test": [5]}
# Kev partition -> {template: output split}. Test is never opened.
HARD_SPLITS = {
    "train": {0: "train", 1: "train", 2: "train", 3: "calibration"},
    "development": {4: "validation"},
}
HARD_ROUND1_EXCLUDED = {"long_policy": "long_policy_excluded_round1_capture_cost"}
HARD_CHOICE_OPTIONS = (3, 6)
HARD_SCORE_LEVELS = 6
HARD_META_REQUIRED = {
    "id",
    "source",
    "group_id",
    "variant",
    "split",
    "template",
    "family",
    "facts",
    "text_sha256",
    "state_tokens",
}
# Small, label-free _meta fields copied into row metadata (never `facts`).
HARD_META_COPY = ("subtype", "state_tokens")
HARD_QUESTION_KEYS = {
    "noul": ({"type", "instructions", "label", "src"}, {"criteria"}),
    "choice": ({"type", "instructions", "criteria", "label", "src"}, set()),
    "score": ({"type", "instructions", "criteria", "label", "src"}, set()),
}
ANONYMOUS_KEY = re.compile(r"[a-z]")
HARD_CAVEATS = [
    "Preparation does not run training; these rows alone do not establish quality.",
    (
        "hard-v1 is synthetic: every label is a family solver applied to the "
        "generator's facts. Gains may not transfer to natural decisions."
    ),
    (
        "hard-v1 test (template 5) was not read, rendered or scored; keep it locked "
        "until the training recipe is frozen."
    ),
    (
        "train.jsonl is regenerated, not downloaded: its sha256 must equal the "
        "manifest's, which only Kev's generator with the pinned tokenizer reproduces."
    ),
    "Validation (template 4) and calibration (template 3) differ from train only in surface template.",
    "Frozen Bonsai features may not match Kev's adapter-trained representations.",
    "A small pilot only exercises the pipeline; its metrics prove nothing.",
]


def kev_render(value, indent: int = 0) -> str:
    """Kev's `kev.api.render`: the text the model reads for a JSON state."""
    pad = "  " * indent
    if value is None:
        return ""
    if isinstance(value, (str, int, float, bool)):
        return str(value)
    if isinstance(value, list):
        return "\n".join(
            f"{pad}- {kev_render(item, indent + 1).lstrip()}" for item in value
        )
    return "\n".join(
        f"{pad}{key}:\n{kev_render(item, indent + 1)}"
        if isinstance(item, (dict, list))
        else f"{pad}{key}: {kev_render(item)}"
        for key, item in value.items()
    )


def load_hard_manifest(kev_dir: Path, expected_sha256: str) -> tuple[dict, str]:
    data = (kev_dir / "manifest.json").read_bytes()
    digest = sha256_hex(data)
    if digest != expected_sha256:
        raise PrepareError(
            f"manifest.json sha256 {digest} does not match pinned {expected_sha256}"
        )
    manifest = json.loads(data, object_pairs_hook=_strict_object)
    expected = {
        "version": HARD_VERSION,
        "partitions": ["train", "development", "test"],
        "families": list(HARD_FAMILIES),
        "templates": {k: list(v) for k, v in HARD_TEMPLATES.items()},
        "trainable_sources": [f"hard_{f}" for f in HARD_FAMILIES],
        "eval_only_sources": [],
        "eval_only": False,
        "tokenizer": HARD_TOKENIZER,
    }
    for key, value in expected.items():
        if manifest.get(key) != value:
            raise PrepareError(f"manifest {key} {manifest.get(key)!r} != {value!r}")
    if "test" not in manifest.get("locked", []):
        raise PrepareError("manifest does not lock the test partition")
    for name in ("train.jsonl", "development.jsonl", "test.jsonl"):
        entry = manifest.get("files", {}).get(name)
        if not isinstance(entry, dict) or not all(
            isinstance(entry.get(k), int) for k in ("bytes", "records", "questions")
        ):
            raise PrepareError(f"manifest has no complete files entry for {name}")
        if not isinstance(entry.get("sha256"), str) or not HEX64.fullmatch(
            entry["sha256"]
        ):
            raise PrepareError(f"manifest {name} lacks a sha256")
    return manifest, digest


def load_hard_partition(kev_dir: Path, partition: str, manifest: dict) -> list[dict]:
    """Load and fully validate train or development; test is refused."""
    if partition not in HARD_SPLITS:
        raise PrepareError(f"hard-v1 partition {partition!r} is never read")
    name = f"{partition}.jsonl"
    entry = manifest["files"][name]
    data = (kev_dir / name).read_bytes()
    digest = sha256_hex(data)
    if digest != entry["sha256"]:
        raise PrepareError(
            f"{name}: sha256 {digest} does not match manifest {entry['sha256']}"
        )
    if len(data) != entry["bytes"]:
        raise PrepareError(f"{name}: {len(data)} bytes, manifest says {entry['bytes']}")
    lines = data.decode("utf-8").split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    records = []
    for number, line in enumerate(lines, 1):
        where = f"{name}:{number}"
        try:
            record = json.loads(line, object_pairs_hook=_strict_object)
        except (json.JSONDecodeError, PrepareError) as error:
            raise PrepareError(f"{where}: invalid JSON record: {error}") from error
        check_hard_record(record, partition, where)
        records.append(record)
    questions = sum(len(r["questions"]) for r in records)
    if (len(records), questions) != (entry["records"], entry["questions"]):
        raise PrepareError(
            f"{name}: {len(records)} records / {questions} questions, manifest says "
            f"{entry['records']} / {entry['questions']}"
        )
    by_family = entry.get("by_family")
    if isinstance(by_family, dict):
        seen = defaultdict(lambda: [0, 0])
        for r in records:
            seen[r["_meta"]["family"]][0] += 1
            seen[r["_meta"]["family"]][1] += len(r["questions"])
        declared = {
            f: [v.get("records"), v.get("questions")] for f, v in by_family.items()
        }
        if dict(seen) != declared:
            raise PrepareError(
                f"{name}: per-family counts {dict(seen)} != manifest {declared}"
            )
    return records


def check_hard_record(record, partition: str, where: str) -> None:
    if not isinstance(record, dict) or set(record) != RECORD_KEYS:
        raise PrepareError(
            f"{where}: record must have exactly the keys {sorted(RECORD_KEYS)}"
        )
    meta = record["_meta"]
    if not isinstance(meta, dict) or not HARD_META_REQUIRED <= set(meta):
        raise PrepareError(f"{where}: _meta must include {sorted(HARD_META_REQUIRED)}")
    family = meta["family"]
    if family not in HARD_FAMILIES:
        raise PrepareError(f"{where}: unsupported family {family!r}")
    if meta["source"] != f"hard_{family}":
        raise PrepareError(f"{where}: source {meta['source']!r} for family {family}")
    if meta["split"] != partition or meta["variant"] != "clean":
        raise PrepareError(f"{where}: _meta split/variant {meta['split']!r}/{meta['variant']!r}")
    prefix = f"hard-v1/{family}/{partition}/"
    if not re.fullmatch(re.escape(prefix) + r"\d{5}", str(meta["id"])):
        raise PrepareError(f"{where}: unexpected id {meta['id']!r}")
    if meta["group_id"] != meta["id"] and not re.fullmatch(
        re.escape(prefix) + r"g\d{5}", str(meta["group_id"])
    ):
        raise PrepareError(f"{where}: unexpected group_id {meta['group_id']!r}")
    match = re.fullmatch(re.escape(family) + r"/t(\d)", str(meta["template"]))
    if not match or int(match.group(1)) not in HARD_TEMPLATES[partition]:
        raise PrepareError(
            f"{where}: template {meta['template']!r} is not a {partition} template"
        )
    if not isinstance(meta["facts"], dict):
        raise PrepareError(f"{where}: _meta.facts must be an object")
    if type(meta["state_tokens"]) is not int or meta["state_tokens"] < 1:
        raise PrepareError(f"{where}: _meta.state_tokens must be a positive integer")
    if not isinstance(meta["text_sha256"], str) or not HEX64.fullmatch(
        meta["text_sha256"]
    ):
        raise PrepareError(f"{where}: _meta.text_sha256 must be a sha256 hex digest")
    state = record["state"]
    if not isinstance(state, (str, dict, list)) or not kev_render(state).strip():
        raise PrepareError(f"{where}: state must be non-empty text or JSON")
    if normalized_text_hash(kev_render(state)) != meta["text_sha256"]:
        raise PrepareError(f"{where}: _meta.text_sha256 does not match the state")
    questions = record["questions"]
    if not isinstance(questions, dict) or not questions:
        raise PrepareError(f"{where}: questions must be a non-empty object")
    for qid, question in questions.items():
        hard_options(question, f"{where}: {qid}", meta["source"], True)


def _option_name(key: str) -> str:
    return key.replace("_", " ")


def hard_options(question, where: str, source: str, descriptions: bool):
    """Validate one question; return [(option text, native key)] in Kev order."""
    qtype = question.get("type") if isinstance(question, dict) else None
    if qtype not in HARD_QUESTION_KEYS:
        raise PrepareError(f"{where}: unsupported question type {qtype!r}")
    required, optional = HARD_QUESTION_KEYS[qtype]
    if not required <= set(question) <= required | optional:
        raise PrepareError(
            f"{where}: {qtype} question keys {sorted(question)} != {sorted(required)}"
        )
    if question["src"] != source:
        raise PrepareError(f"{where}: src {question['src']!r} != {source!r}")
    if not isinstance(question["instructions"], str) or not question["instructions"].strip():
        raise PrepareError(f"{where}: instructions must be non-empty text")
    label, criteria = question["label"], question.get("criteria")
    if qtype == "noul":
        if type(label) is not bool:
            raise PrepareError(f"{where}: noul label must be a boolean")
        criteria = criteria or {}
        if not isinstance(criteria, dict) or not set(criteria) <= {"true", "false"}:
            raise PrepareError(f"{where}: noul criteria may only describe true/false")
        options = []
        for text, value in NOUL_OPTIONS:
            desc = criteria.get(str(value).lower())
            if desc is not None and not isinstance(desc, str):
                raise PrepareError(f"{where}: noul descriptions must be text")
            options.append((f"{text}: {desc}" if descriptions and desc else text, value))
    elif qtype == "choice":
        low, high = HARD_CHOICE_OPTIONS
        if not isinstance(criteria, dict) or not low <= len(criteria) <= high:
            raise PrepareError(f"{where}: choice needs {low}-{high} options")
        if label not in criteria:
            raise PrepareError(f"{where}: choice label {label!r} is not an option")
        options = []
        for key, desc in criteria.items():
            if not re.fullmatch(r"[a-z0-9]+(_[a-z0-9]+)*", key):
                raise PrepareError(f"{where}: unsupported option key {key!r}")
            if desc is not None and not isinstance(desc, str):
                raise PrepareError(f"{where}: option {key!r} description must be text")
            if ANONYMOUS_KEY.fullmatch(key):
                if not desc:
                    raise PrepareError(f"{where}: anonymous option {key!r} has no text")
                text = desc
            elif descriptions and desc:
                text = f"{_option_name(key)}: {desc}"
            else:
                text = _option_name(key)
            options.append((text, key))
    else:
        if not isinstance(criteria, list) or len(criteria) != HARD_SCORE_LEVELS:
            raise PrepareError(f"{where}: score needs {HARD_SCORE_LEVELS} levels")
        if type(label) is not int or not 0 <= label < len(criteria):
            raise PrepareError(f"{where}: score label must be a level index")
        if not all(isinstance(level, str) and level for level in criteria):
            raise PrepareError(f"{where}: score levels must be non-empty text")
        options = [(level, index) for index, level in enumerate(criteria)]
    texts = [text for text, _ in options]
    if len(set(texts)) != len(texts) or any("\n" in t or not t.strip() for t in texts):
        raise PrepareError(f"{where}: option texts must be distinct single lines")
    return options


def hard_candidates(records_by_partition, seed, excluded, descriptions, include):
    renderer = HARD_RENDERER if descriptions else HARD_RENDERER_NO_DESCRIPTIONS
    seen = {}
    for partition, records in records_by_partition.items():
        for record in records:
            meta = record["_meta"]
            row_sha = sha256_hex(
                json.dumps(record, sort_keys=True, ensure_ascii=False).encode("utf-8")
            )
            for key in (meta["id"], row_sha):
                if key in seen:
                    raise PrepareError(f"record {key} repeats ({seen[key]}, {partition})")
                seen[key] = partition
            family = meta["family"]
            if family in HARD_ROUND1_EXCLUDED and family not in include:
                reason = HARD_ROUND1_EXCLUDED[family]
                excluded[reason][partition][f"{family}/records"] += 1
                excluded[reason][partition][f"{family}/questions"] += len(
                    record["questions"]
                )
                continue
            template = int(meta["template"].rsplit("/t", 1)[1])
            split = HARD_SPLITS[partition][template]
            state_text = kev_render(record["state"])
            for qid, question in record["questions"].items():
                options = hard_options(question, meta["id"], meta["source"], descriptions)
                if question["type"] == "noul":
                    options = permute_options(options, seed, f"{meta['id']}/{qid}")
                text, ends = render(state_text, question["instructions"], options)
                keys = [value for _, value in options]
                yield {
                    "id": f"kev-{HARD_VERSION}/{meta['id'].split('/', 1)[1]}/{qid}",
                    "text": text,
                    "token_end_offsets": ends,
                    "metadata": {
                        "split": split,
                        "dataset": HARD_VERSION,
                        "target": keys.index(question["label"]),
                        "options": [t for t, _ in options],
                        "option_labels": keys,
                        "option_count": len(options),
                        "native_label": question["label"],
                        "task": family,
                        "family": family,
                        "question": qid,
                        "question_type": question["type"],
                        "source": meta["source"],
                        "template": meta["template"],
                        "kev_id": meta["id"],
                        "group_id": meta["group_id"],
                        "kev_partition": partition,
                        "row_sha256": row_sha,
                        "text_sha256": meta["text_sha256"],
                        "renderer": renderer,
                        **{k: meta.get(k) for k in HARD_META_COPY},
                    },
                    "_state": json.dumps(
                        record["state"], sort_keys=True, ensure_ascii=False
                    ),
                    "_state_text": state_text,
                }


def check_hard_splits(rows, min_groups: int, families) -> dict:
    """Overlaps, then per split and family: groups, label diversity per question
    type, and coverage of every train (family, question type) cell."""
    check_overlaps(rows)
    cells = defaultdict(list)
    for row in rows:
        meta = row["metadata"]
        cells[(meta["split"], meta["family"])].append(row)
    train_types = {
        (f, r["metadata"]["question_type"])
        for (s, f), cell in cells.items()
        if s == "train"
        for r in cell
    }
    counts = {}
    for split in ("train", "calibration", "validation"):
        counts[split] = {}
        for family in families:
            cell = cells.get((split, family), [])
            groups = {r["metadata"]["group_id"] for r in cell}
            if len(groups) < min_groups:
                raise PrepareError(
                    f"{split}/{family}: {len(groups)} groups, need {min_groups}"
                )
            by_type = defaultdict(list)
            for r in cell:
                by_type[r["metadata"]["question_type"]].append(r)
            for qtype in sorted({t for f, t in train_types if f == family}):
                if qtype not in by_type:
                    raise PrepareError(f"{split}/{family}: no {qtype} questions")
            types = {}
            for qtype, typed in sorted(by_type.items()):
                labels = Counter(
                    json.dumps(r["metadata"]["native_label"]) for r in typed
                )
                targets = Counter(
                    f"{r['metadata']['target']}/{r['metadata']['option_count']}"
                    for r in typed
                )
                if len(labels) < 2:
                    raise PrepareError(
                        f"{split}/{family}/{qtype}: one class only "
                        f"(labels {dict(labels)}, targets {dict(targets)})"
                    )
                types[qtype] = {
                    "rows": len(typed),
                    "questions": dict(
                        sorted(Counter(r["metadata"]["question"] for r in typed).items())
                    ),
                    "option_counts": dict(
                        sorted(
                            Counter(str(r["metadata"]["option_count"]) for r in typed).items()
                        )
                    ),
                    "targets": dict(sorted(targets.items())),
                }
            counts[split][family] = {
                "rows": len(cell),
                "records": len({r["metadata"]["kev_id"] for r in cell}),
                "groups": len(groups),
                "templates": dict(
                    sorted(Counter(r["metadata"]["template"] for r in cell).items())
                ),
                "question_types": types,
            }
    return counts


def _rows_payload(rows) -> bytes:
    return "".join(
        json.dumps(
            {k: r[k] for k in ("id", "text", "token_end_offsets", "metadata")},
            ensure_ascii=False,
            sort_keys=True,
        )
        + "\n"
        for r in rows
    ).encode("utf-8")


def prepare_hard_v1(
    kev_dir: Path,
    out: Path,
    *,
    seed: str = DEFAULT_SEED,
    pilot_rows: int | None = None,
    min_groups: int = 2,
    manifest_sha256: str = HARD_MANIFEST_SHA256,
    option_descriptions: bool = True,
    include_families: tuple[str, ...] = (),
) -> dict:
    """Validate Kev hard-v1 train/development and write rows.jsonl + report.json."""
    kev_dir, out = Path(kev_dir), Path(out)
    if out.exists() or out.is_symlink():
        raise PrepareError(f"{out} already exists; refusing to overwrite")
    if min_groups < 1 or (pilot_rows is not None and pilot_rows < 1):
        raise PrepareError("min groups and pilot rows must be positive")
    unknown = set(include_families) - set(HARD_ROUND1_EXCLUDED)
    if unknown:
        raise PrepareError(f"only {sorted(HARD_ROUND1_EXCLUDED)} can be included, not {sorted(unknown)}")
    manifest, manifest_digest = load_hard_manifest(kev_dir, manifest_sha256)
    records = {p: load_hard_partition(kev_dir, p, manifest) for p in HARD_SPLITS}
    excluded = defaultdict(lambda: defaultdict(Counter))
    rows = list(
        hard_candidates(records, seed, excluded, option_descriptions, set(include_families))
    )
    if pilot_rows is not None:
        rows = apply_pilot_cap(rows, seed, pilot_rows, excluded)
    present = {r["_meta"]["family"] for part in records.values() for r in part}
    families = [
        f
        for f in HARD_FAMILIES
        if f in present and (f not in HARD_ROUND1_EXCLUDED or f in include_families)
    ]
    counts = check_hard_splits(rows, min_groups, families)
    rows.sort(
        key=lambda r: (
            SPLIT_ORDER.index(r["metadata"]["split"]),
            hash_key(seed, "order", r["id"]),
        )
    )
    payload = _rows_payload(rows)
    files = manifest["files"]
    report = {
        "format": FORMAT,
        "dataset": HARD_VERSION,
        "renderer": HARD_RENDERER if option_descriptions else HARD_RENDERER_NO_DESCRIPTIONS,
        "options": {
            "seed": seed,
            "pilot_rows": pilot_rows,
            "min_groups": min_groups,
            "option_descriptions": option_descriptions,
            "include_families": sorted(include_families),
        },
        "kev": {
            "repository": KEV_REPOSITORY,
            "revision": HARD_REVISION,
            "generator": "scripts/build_hard_v1.py",
            "manifest_url": f"{HARD_BASE_URL}/manifest.json",
            "manifest_sha256": manifest_digest,
            "manifest_pinned": manifest_digest == HARD_MANIFEST_SHA256,
            "version": manifest["version"],
            "seed": manifest.get("seed"),
            "tokenizer": manifest["tokenizer"],
            "code_sha256": manifest.get("code_sha256"),
            "licence": (
                "Apache-2.0 (Kev repository: generator code and its programmatic "
                "output); no third-party source text"
            ),
            "labels": manifest.get("labels"),
            "files": {
                name: {
                    **{k: files[name][k] for k in ("sha256", "bytes", "records", "questions")},
                    "read": name != "test.jsonl",
                }
                for name in ("train.jsonl", "development.jsonl", "test.jsonl")
            },
        },
        "split_map": {
            "train": "Kev train, templates 0-2",
            "calibration": "Kev train, template 3",
            "validation": "Kev development, template 4",
            "test": "Kev test, template 5: locked, not read",
        },
        "translation": {
            "noul": "Yes/No (Kev true/false), seeded per-row order",
            "choice": f"{HARD_CHOICE_OPTIONS[0]}-{HARD_CHOICE_OPTIONS[1]} options, Kev order; "
            "underscores read as spaces; single-letter keys show their description only",
            "score": f"{HARD_SCORE_LEVELS} ordered levels; target is the level index",
        },
        "counts": counts,
        "excluded_rows": {
            reason: {
                part: dict(sorted(c.items())) for part, c in sorted(by_part.items())
            }
            for reason, by_part in sorted(excluded.items())
        },
        "output": {
            "rows": "rows.jsonl",
            "row_count": len(rows),
            "sha256": sha256_hex(payload),
        },
        "caveats": HARD_CAVEATS,
    }
    out.mkdir(parents=True)
    with open(out / "rows.jsonl", "xb") as handle:
        handle.write(payload)
    with open(out / "report.json", "x", encoding="utf-8") as handle:
        handle.write(
            json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        )
    return report


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--kev-dir",
        type=Path,
        required=True,
        help="directory with manifest.json, train/development/test.jsonl",
    )
    parser.add_argument("--out", type=Path, required=True, help="new output directory")
    parser.add_argument("--seed", default=DEFAULT_SEED)
    parser.add_argument(
        "--dataset",
        choices=(KEV_VERSION, HARD_VERSION),
        default=KEV_VERSION,
        help="Kev suite layout (default devtools-v1)",
    )
    parser.add_argument(
        "--calibration-fraction",
        type=float,
        default=None,
        help="devtools-v1 only (default 0.1); hard-v1 calibrates on template 3",
    )
    parser.add_argument(
        "--pilot-rows",
        type=int,
        default=None,
        help="per split and task, keep whole groups up to N rows",
    )
    parser.add_argument(
        "--min-groups", type=int, default=2, help="minimum groups per split and task"
    )
    parser.add_argument(
        "--manifest-sha256",
        default=None,
        help="override only for test fixtures; defaults to the dataset's pin",
    )
    parser.add_argument(
        "--no-option-descriptions",
        action="store_true",
        help="hard-v1 only: render named options without their descriptions",
    )
    parser.add_argument(
        "--include-long-policy",
        action="store_true",
        help="hard-v1 only: keep long_policy (excluded in round 1)",
    )
    args = parser.parse_args(argv)
    try:
        if args.dataset == HARD_VERSION:
            if args.calibration_fraction is not None:
                raise PrepareError("hard-v1 calibrates on template 3, not a fraction")
            report = prepare_hard_v1(
                args.kev_dir,
                args.out,
                seed=args.seed,
                pilot_rows=args.pilot_rows,
                min_groups=args.min_groups,
                manifest_sha256=args.manifest_sha256 or HARD_MANIFEST_SHA256,
                option_descriptions=not args.no_option_descriptions,
                include_families=("long_policy",) if args.include_long_policy else (),
            )
        else:
            if args.no_option_descriptions or args.include_long_policy:
                raise PrepareError("option descriptions and long_policy are hard-v1 options")
            report = prepare(
                args.kev_dir,
                args.out,
                seed=args.seed,
                calibration_fraction=(
                    0.1 if args.calibration_fraction is None else args.calibration_fraction
                ),
                pilot_rows=args.pilot_rows,
                min_groups=args.min_groups,
                manifest_sha256=args.manifest_sha256 or PINNED_MANIFEST_SHA256,
            )
    except (PrepareError, OSError, UnicodeDecodeError) as error:
        print(f"judgment_prepare: {error}", file=sys.stderr)
        return 2
    print(
        json.dumps({"counts": report["counts"], "output": report["output"]}, indent=2)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
